### ISSUE TITLE
Handle empty rules

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume-css#10]
Blocked by #2 

```css
.cow {}
.cow .dog { padding: 8px }
```
```html
<div class="cow">
  <div class="dog"></div>
</div>
```
