### ISSUE TITLE
Handle At-rules (@media, @keyframes, etc)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume-css#13]
MDN lists these as all the At-rules, though this list may be incomplete:

At-rule name             | Type         | Atomize? | Link
:--                      | :--          | :--      | :--
`@document`              | Grouping     | Yes ✔️  | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)
`@-moz-document`         | Grouping     | Yes ✔️  | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)
`@layer`                 | Double Group | Yes ✔️  | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
`@media`                 | Double Group | Yes ✔️  | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media)
`@supports`              | Double Group | Yes ✔️  | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports)
`@charset`               | 1 line       | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@charset)
`@import`                | 1 line       | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import)
`@namespace`             | 1 line       | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace)
`@font-feature-values`   | Double Group | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values)
`@keyframes`             | Double Group | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes)
`@page`                  | Double Group | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@page)
`@color-profile`         | Grouping     | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@color-profile)
`@counter-style`         | Grouping     | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style)
`@font-face`             | Grouping     | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face)
`@property`              | Grouping     | No       | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@property)
`@viewport` (deprecated) | Grouping     | No       | [janky site](https://www.educba.com/css-viewport/)

Some `@` rules can contain CSS classes, they have been noted in the table with "Atomize? Yes".

For anything else, it should just pass through to the output CSS file untouched.

**Example:**

```css
/* INPUT */
@media screen and (min-width: 900px) {
  .example {
    padding: 8px;
    margin: 12px;
  }
}
```

```css
/* ATOMIZED */
@media screen and (min-width: 900px) {
  /* rp__@media screen and (min-width:900px){padding:8px} */
  .rp____--ATSIGNmedia_____-screen_____-and_____-__--OPENPARENmin-width__--COLON900px__--CLOSEPAREN__--OPENCURLYBRACEpadding__--COLON8px__--CLOSECURLYBRACE {
    padding: 8px;
  }
  /* rp__@media screen and (min-width:900px){margin:12px} */
  .rp____--ATSIGNmedia_____-screen_____-and_____-__--OPENPARENmin-width__--COLON900px__--CLOSEPAREN__--OPENCURLYBRACEmargin__--COLON12px__--CLOSECURLYBRACE {
    margin: 12px;
  }
}
```

```css
/* ATOMIZED (uglified) */
@media screen and (min-width: 900px) {
  .rp__0 {
    padding: 8px;
  }
  .rp__1 {
    margin: 12px;
  }
}
```

We need a way to group and differentiated atomized classes that are in unique media query groups. My idea here is to prefix it with the full name/details of the query, then an open curly brace, then the declaration name and value, then a closing curly brace.

The `@document` and `@-moz-document` rules can wrap an entire CSS file, so would need extra opening/closing curly braces as well in their encoded name.

**Example:**

```css
/* INPUT */
@document url("http://www.w3.org/"), media-document("video") {
  @media screen and (min-width: 900px) {
    .example {
      padding: 8px;
      margin: 12px;
    }
  }
}
```

```css
/* ATOMIZED */
@document url("http://www.w3.org/"), media-document("video") {
  @media screen and (min-width: 900px) {
    /* rp__@document url("http://www.w3.org/"),media-document("video"){@media screen and (min-width:900px){padding:8px}} */
    .rp____--ATSIGNdocument_____-url__--OPENPAREN__--DOUBLEQUOTEhttp__--COLON__--FORWARDSLASH__--FORWARDSLASHwww__--DOTw3__--DOTorg__--FORWARDSLASH__--DOUBLEQUOTE__--CLOSEPAREN__--COMMAmedia-document__--OPENPAREN__--DOUBLEQUOTEvideo__--DOUBLEQUOTE__--CLOSEPAREN__--OPENCURLYBRACE__--ATSIGNmedia_____-screen_____-and_____-__--OPENPARENmin-width__--COLON900px__--CLOSEPAREN__--OPENCURLYBRACEpadding__--COLON8px__--CLOSECURLYBRACE__--CLOSECURLYBRACE {
      padding: 8px;
    }
    /* rp__@document url("http://www.w3.org/"),media-document("video"){@media screen and (min-width:900px){margin:12px}} */
    .rp____--ATSIGNdocument_____-url__--OPENPAREN__--DOUBLEQUOTEhttp__--COLON__--FORWARDSLASH__--FORWARDSLASHwww__--DOTw3__--DOTorg__--FORWARDSLASH__--DOUBLEQUOTE__--CLOSEPAREN__--COMMAmedia-document__--OPENPAREN__--DOUBLEQUOTEvideo__--DOUBLEQUOTE__--CLOSEPAREN__--OPENCURLYBRACE__--ATSIGNmedia_____-screen_____-and_____-__--OPENPARENmin-width__--COLON900px__--CLOSEPAREN__--OPENCURLYBRACEmargin__--COLON12px__--CLOSECURLYBRACE__--CLOSECURLYBRACE {
      margin: 12px;
    }
  }
}
```

```css
/* ATOMIZED (uglified) */
@document url("http://www.w3.org/"), media-document("video") {
  @media screen and (min-width: 900px) {
    .rp__0 {
      padding: 8px;
    }
    .rp__1 {
      margin: 12px;
    }
  }
}
```
These encoded classnames can get pretty long, but browsers allow class names to be any length (no limit), and also users are just gonna use the uglified version anyway.
