### ISSUE TITLE
Handle Qualifying Elements (CSS)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [red-perfume/red-perfume-css#7]
```css
h1.example {
  display: block;
  text-align: center;
}
```
should become
```css
h1.rp____---TAG_h1_display__--COLONblock {
  display: block;
}
h1.rp____---TAG_h1_text-align__--COLONcenter {
  text-align: center;
}
```
or if uglified
```css
h1.rp__0 {
  display: block;
}
h1.rp__1 {
  text-align: center;
}
```
